version: 2.1

build:
    
    # Primary container image where all commands run
    
  docker:
    - image: circleci/node:10.16.3
      environment:
        DATABASE_URL: postgresql://root@localhost/circle_test
          
    # Service container image
    
    - image: circleci/postgres:9.6.5-alpine-ram
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
